name: Build Single HTML Game
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Create Single HTML
        run: |
          # Устанавливаем упаковщик
          npm install -g inliner
          # Склеиваем всё в один файл. 
          # Мы берем index.html из папки dist, куда его положил npm run build
          inliner dist/index.html > game_final.html

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: My-Single-File-Game
          # Указываем путь ТОЛЬКО к одному файлу, чтобы не было лишних папок
          path: game_final.html
